### ISSUE TITLE
Symantec is blocking CLI install on Windows

### ISSUE THREAD

**Issue by zsjenei** [phrase/phrase-cli#102]
All windows versions are blocked by Symantec. Could you please request whitelisting? As I can see, this is a returning issue.

**Comment by theSoenke** [comment]
Hey @zsjenei, we're currently looking into whitelisting the CLI. Unfortunately, the site to report false positives is currently not working. We'll check again in a bit whether it works again

**Comment by theSoenke** [comment]
@zsjenei thanks, that URL worked. I've reached out to them a few days ago but didn't really get any feedback yet

**Comment by zsjenei** [comment]
@theSoenke actually it worked, it is not blocked any more by Symantec! Thank you! I am closing the issue.
