### ISSUE TITLE
null value on phrase pull leads into exception

### ISSUE THREAD

**Issue by komarekw** [phrase/phrase-cli#104]
Hi,
we are just trying to pull our localizations from phrase. As we could have not translated keys, we are using the `include_empty_translations: true` param in our .phrase.yml. Now we are getting the untranslated keys with null value. When I now run any command for analyzing or pub get from flutter we get an exception `Exception: A value for resource <our_key_name> was not found.`. 

Can someone give me any hint, how to fix this?

Thanks,
Werner

**Comment by theSoenke** [comment]
Hey @komarekw, would it be a solution to remove the parameter `include_empty_translations: true` if you don't need the empty translations? Or what would be the expected behavior with the parameter `include_empty_translations: true` for you?

**Comment by theSoenke** [comment]
Thanks for the feedback. If nil values are not allowed then it looks like it should be empty strings instead. We're investigating about changing it to empty strings

**Comment by forelabs** [comment]
@komarekw Can you please name the file format you are using to pull the translations?

**Comment by theSoenke** [comment]
Hi @komarekw, could you check again whether this now works for you with arb files? This should be solved now and empty strings instead of null returned
