### ISSUE TITLE
Branch created successfully but Phrase.com Dashboard says "could not be created".

### ISSUE THREAD

**Issue by WaKeMaTTa** [phrase/phrase-cli#109]
Hello,

I run these 2 commands successfully:

```bash
bin/phrase branches create \
  --project_id ABCD \
  --data "{\"name\": \"sc-38517-step-2\"}"

bin/phrase push \
  --branch `git branch --show-current` \
  --wait
```

But when I check in `phrase.com` > `project` > `branches`, I get the message `could not be created`:

![image](https://user-images.githubusercontent.com/3450257/184367115-0e1d54e6-1031-40f8-84ed-963610e19de6.png)

**Why?**

---

### UPDATE 1

One more detail, when I visit the URL: https://app.phrase.com/accounts/wecasa/projects/PROJECT_NAME/branches?branch=sc-38517-step-4

I can see the changes of that branch like normal.

---

### UPDATE 2

I found that if I don't run 

```bash
bin/phrase branches create \
  --project_id 30d2a4a2a5cd9b39e6c990c26c0b33cc \
  --data "{\"name\": \"sc-38517-step-2\"}" \
```

I do NOT get the message `could not be created`.

Strange :confused:

**Comment by WaKeMaTTa** [comment]
@forelabs I run the command one after the other. 

Can you implement `phrase branches create --wait`?  (Like we have in `phrase push --wait`)

**Comment by forelabs** [comment]
@forelabs Thanks for the feature request. It will provide a better user experience for integrations so we will try to have it on our roadmap as soon as possible.

Just out of curiosity: Why do you create a branch and merge it right after? The typically workflow would be to get new translations in that newly created branch.

**Comment by WaKeMaTTa** [comment]
> Just out of curiosity: Why do you create a branch and merge it right after?

Sorry, I updated my initial message of this issue. We use `phrase branches create` and then `phrase push`.

**Comment by theSoenke** [comment]
Hi @WaKeMaTTa, it is also possible to pass a branch to the push command. So if you want to create a new branch and upload translations you can run `phrase push --branch <branch_name>`. This will either create a new branch or use an existing one if present
