### ISSUE TITLE
Provide CLI as binary npm package

### ISSUE THREAD

**Issue by nlopin** [phrase/phrase-cli#110]
Hello! I'm not sure where should I write the request, point me to the right direction please.

When used in CI, Phrase provides not the greatest develoepr experience. If Docker is used, it requires a developer to find the correct url to the CLI on the website, install it, give execution permissions and then run.

In web projects it usually expected that project can setup itself by only using npm and npx commands. It would be nice to have `phrase-cli` published in [npm as binary package](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#bin), so the user can just do `npx phrase pull` in the project to get all the translations.

What do you think?

**Comment by nlopin** [comment]
Folks, I don't understand why you use GitHub if this boilerplate is an answer to an issue.

**Comment by forelabs** [comment]
Hi @nlopin ,

I am sorry that our communication flow did not worked great in your case.
Thanks for the idea of bringing phrase cli to the npm repository. Unfortunately we have no plans to prioritize this request for the time being.

Tip: If you are using mac the phrase cli is part of homebrew.

**Comment by nayaabkhan** [comment]
@nlopin We've got a similar use case – We'd like to download phrases for building our project on Vercel (CD). Currently, the workaround is to `wget` the binary from GitHub, while possible it becomes a little cumbersome to write a single line to download for all platforms our devs are on.

I'm considering to create a package myself at the moment with a `postinstall` script to download the correct binary for the platform and architecture. Regardless, I believe the PhraseApp team should consider owning and maintaining the package.

**Comment by nayaabkhan** [comment]
I've shipped the first version of this.

Source: https://github.com/nayaabkhan/phrase-cli
Package: https://www.npmjs.com/package/phrase-cli

It is only tested on macOS ARM64 because that's what I use. Also, I'm yet to upload the packages for Linux-32 and Linux-ARM because of the 24-hour policy of NPM for removed packages.

**Comment by nlopin** [comment]
Thank you @nayaabkhan 👍 Great work
