### ISSUE TITLE
Provide docker image for arm64

### ISSUE THREAD

**Issue by sja** [phrase/phrase-cli#118]
The current docker images phrase/phrase-cli are just for linux/amd64. Apple silicon needs arm64.

**Comment by theSoenke** [comment]
Hey @sja, thanks for the suggestion. I will check this and I hope we can add the arm docker image soon

**Comment by theSoenke** [comment]
I've just published an linux/arm64 image for the latest version 2.6.3. Let me know in case anything is not working as expected
