### ISSUE TITLE
Take `setup-phraseapp` GitHub Action under `phrase` org

### ISSUE THREAD

**Issue by iamandrewluca** [phrase/phrase-cli#119]
Hey there!

I want to propose you take under your wing [winify-ag/setup-phraseapp](https://github.com/winify-ag/setup-phraseapp) GitHub Action or, maybe create a new one and we can redirect everyone there.

I don't use the action anymore and don't have too much interest in maintaining it now. Although I see people have interest in it.

A few jobs ago when I was at Winify, I created this action, that downloads Phrase CLI.
I don't work there for a few years now, and the company also does not exist anymore.

Thanks for your understanding!

**Comment by theSoenke** [comment]
Hi @iamandrewluca, thank you for sharing. We also had some ideas to provide a similar action ourselves. So this works perfectly if you already built one! :tada:  Hope in the next few weeks I'll have some time to to take a closer look and take over the maintenance to make it an officially supported action

**Comment by iamandrewluca** [comment]
Instead of transferring the repo. I would recommend starting from scratch using [`actions/javascript-action`](https://github.com/actions/javascript-action) which has better practices and is up to date, and just take the code from the original repo, which is under MIT Licence

**Comment by skeeping** [comment]
@theSoenke Once this has been decided please make a post on winify-ag/setup-phraseapp to let people know what is decided what is available for us to use.

**Comment by iamandrewluca** [comment]
@skeeping when `phrase` makes an official action, I will add that info to the `setup-phraseapp` repo

**Comment by jablan** [comment]
@iamandrewluca We created https://github.com/phrase/setup-cli

**Comment by iamandrewluca** [comment]
@jablan Cool, Cool, Cool!!!
I will add a message to our repo, and redirect everyone to the new GitHub Action!
