### ISSUE TITLE
About release 2.6.6

### ISSUE THREAD

**Issue by chenrui333** [phrase/phrase-cli#120]
👋 it looks like the release process was not completed, at least the tag did not get marked as latest. Raise this issue for awareness, thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/122235

**Comment by theSoenke** [comment]
Hey :wave: Thanks for raising it. This has now been fixed and released https://github.com/phrase/phrase-cli/releases/tag/2.6.6 Maybe you could update your PR now or if you close it I can retrigger the automatic brew release action again: https://github.com/phrase/phrase-cli/actions/runs/4091322098/jobs/7055323453

**Comment by theSoenke** [comment]
Thanks for updating the PR. Everything should be working now
