### ISSUE TITLE
Public changelog for the phrase CLI?

### ISSUE THREAD

**Issue by skyfrk** [phrase/phrase-cli#124]
Hey there,

I'm just wondering if there is a public changelog for the phrase CLI somewhere. Everytime I update the pinned phrase CLI version in our integration I wonder what has changed and if we can improve our integration with new features. 🤔

**Comment by jablan** [comment]
Hi @skyfrk, thanks for raising the issue. We are aware of the need for a decent CHANGELOG and we opened an internal ticket to tackle this. Hopefully we'll start publishing one soon.

**Comment by jablan** [comment]
Not sure if I could call it soon :sweat_smile:, but finally we started automatic generating of changelogs for https://github.com/phrase/openapi, which should also trickle down to this repo too (hopefully to be seen in action soon)
