### ISSUE TITLE
Unable to login after Android Studio Update

### ISSUE THREAD

**Issue by CebotariM** [phrase/phrase-cli#125]
Hi, i updated AS to the latest version:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/12050680/222104675-d2f27b69-2a7b-4efc-a1a8-00eef01f1524.png">
after which phrase plugin stopped working:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/12050680/222104844-5ee2a0d7-f913-4209-983f-c78a5d9f8c9f.png">
no changes were made on server, or local config
Steps tried :
 - reinstalled AS plugin
 - reinstalled phrase-cli
 Trying to do the same action from cli resulted in this error:
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/12050680/222105680-3ff451e0-4906-4b10-ae46-14b147111601.png">
please note that no changes were made to the key, or project, only updated AS

**Comment by jablan** [comment]
hi @CebotariM, regarding the 404 error, how does your `.phrase.yml` look like?

Regarding the "invalid token", is the token created on us.app.phrase.com or app.phrase.com? The API must match the app the token was created in.

**Comment by theSoenke** [comment]
Hi  @CebotariM, I hope it's okay that I've removed the screenshot because with a bit of guessing it might have been possible to extract the token. I would also suggest to disable the token to be safe. 

When you're using the US datacenter you can select it in the config by setting:

```yaml
phrase:
  host: https://api.us.app.phrase.com/v2
```

**Comment by CebotariM** [comment]
Thanks for your suggestion, and removing the screens, unfortunately adding the host in config did not change anything. My assumption is maybe it is something related with the AS plugin? Will keep investigating

**Comment by jablan** [comment]
@CebotariM can't be related with AS if you keep getting the error even when invoking `phrase` manually. just to confirm, you are getting the same 404 error even when running it manually from the directory where `.phrase.yml` is (with `host` set in it)?

**Comment by CebotariM** [comment]
No, if i run cli in the project folder, i get this:
![image](https://user-images.githubusercontent.com/12050680/222162788-25d15f12-08de-44d9-b992-64c5ce03e3ae.png)
now i know that is says that the token is not valid, but i dont think that is the problem, because the same token works for the iOS project, and nothing has changed in the project

**Comment by jablan** [comment]
both errors suggest that there is some confusion between the DCs.

please double-check that

1) the token is created on the same app whose API is used
2) the project with the given ID exists in the same DC

However, we did discover that the AS plugin does not work with custom `host` parameter in the configuration file, and we opened an internal ticket to fix that.

**Comment by CebotariM** [comment]
Hi @jablan, thanks for your investigation and effort. Fortunately (or not) it was a project administration issue, a certain someone changed the tokens and forgot to notify the devs. Sorry to take your time :)
