### ISSUE TITLE
[Question] Ignore specific key with phrase-pull command

### ISSUE THREAD

**Issue by berger89** [phrase/phrase-cli#128]
Question:
Is it possible to ignore a specific key when using the phrase-pull command?

**Comment by jablan** [comment]
@berger89 not directly, but you could use tags to tag everything you want to be exported, and then use it when `pull`ing. or you can use [review workflow](https://support.phrase.com/hc/en-us/articles/5784094755484-Review-Workflow-Strings-) and keep the translation you want in unverified state.
