### ISSUE TITLE
Request: only update phrase translations 'newer' with `update_translations`

### ISSUE THREAD

**Issue by joelharkes** [phrase/phrase-cli#133]
there is an option: update_translations in phrase but it overwrites everything.

It would be much more useful to have a following option:
Update all translations keys of which the translation for this key is not found in phrase history.

This way we can update translations in code, and someone else can update other translation keys in phrase and they don't get overwritten when we push our code/translations files only the ones we actually change are updated.

**Comment by joelharkes** [comment]
@docstun do you have an update?

**Comment by jablan** [comment]
@joelharkes isn't that the behaviour you get when you don't use `update_translations` switch?

**Comment by joelharkes** [comment]
@jablan that would not update translation keys of which you've update the translations in your code but not in Phrase.
they would not be updated in Phrase and would later reset back to old translations when importing phrase translations back into your code.

**Comment by joelharkes** [comment]
imagen following use case:

1. Engineer adds translation key 'key1'.
2. github action pushes translation to phrase
3. github action pulls translations from phrase => no change 👍
4. Translator updates 'key2' translation in prhase.
5. Engineer changes translation for 'key1' because of some feature development or bugfix.
6. github action pushes translations to phrase 
   - update_translation: false => key1 is not updated in phrase 🔴
   - update_translation: true => key2 is overwritten with old value from code 🔴
 
 
 Ideally there is an option that overrides only translation keys of which phrase actually registers new changes:
- key2 is not updated as phrase knows pushed translation is a previous known translation in phrase translation history
- key1 is updated as translation of key1 was not yet known in phrase thus expects this to be changed by engineer.

## How we work

on merge of pull request to the main branch the new changes are pushed to phrase via github action.

## Problem

But if engineer has to change some code which includes an existing translation he then separately has to change this in phrase.

often change i code and translation go together. so this is very frustrating.
Making a new translation key is not always a valid solution as the key often is has right name.

**Comment by joelharkes** [comment]
@jablan we do that but we also push more regularly (multiple pull requests per day) so any push could overwrite any change.

Is there a way to extract all changes from a branch and trigger some kind of webhook/api call to run a github action so they can be directly added to github code base?

**Comment by joelharkes** [comment]
@jablan is there a way to get all branches via API/SDK and pull only the changes from that branch? That would be ideal :)

**Comment by joelharkes** [comment]
It would be great if https://support.phrase.com/hc/en-us/articles/5784125562012-GitHub-Strings-
could work well with Phrase branches => each branch makes a Github Pull request

**Comment by joelharkes** [comment]
Possible solution could be to manually checked update_at of each translation that is changed when updating phrase changes:
https://developers.phrase.com/api/#get-/projects/-project_id-/keys/-key_id-/translations => if not changed in last days changes are overwritten by code.

**Comment by jablan** [comment]
@joelharkes I believe you could work around your problem using branching feature. Pushing from CLI relies on upload feature from the core app and adding such a complex behaviour (potentially with big performance impact) unfortunately isn't realistic in the near future.
