### ISSUE TITLE
What's the difference between Phrase-CLI and Phrase-Ruby?

### ISSUE THREAD

**Issue by wow-such-amazing** [phrase/phrase-cli#134]
Hey folks! 

Could you please explain the difference between these repositories? Do they provide the same capabilities, but one is available via brew and another via gem?

- https://github.com/phrase/phrase-ruby
- https://github.com/phrase/phrase-cli

Cheers!

**Comment by jablan** [comment]
The former is Ruby library for accessing Phrase Strings API. The latter is CLI tool (written in golang) for accessing Phrase Strings API.

**Comment by wow-such-amazing** [comment]
@jablan So basically both are doing the same thing? 🤔

**Comment by jablan** [comment]
@wow-such-amazing  well, in the same way a bicycle and a train are doing the same thing. :)

both tools are accessing Phrase Strings API, but Ruby library is used if you have e.g. a Rails app that you wish to communicate with Phrase API, and CLI tool is used standalone, e.g. from bash scripts, github actions and so on. if you write here your use case, I can perhaps advise you on which one of our integrations would suit you the best.

**Comment by wow-such-amazing** [comment]
@jablan I see :D 

In my case I noticed an inconsistency in our ios project setup. Basically I found that we have Phrase gem in Gemfile, but in reality it seems like we actually use Phrase via Brew both locally and when we run the build on Jenkins. So I think I will drop Phrase from Gemfile and will maybe introduce a Brewfile to control the version of Phrase 👀
