### ISSUE TITLE
format_options has invalid keys: enclose_in_cdata

### ISSUE THREAD

**Issue by zeno-mir** [phrase/phrase-cli#14]
Getting `'Targets[0].Params.format_options' has invalid keys: enclose_in_cdata` when running `phrase pull` on an Android project. The same config works as expected with `phraseapp`. This format option still seems to be valid according to https://help.phrase.com/help/android-xml 
Any help will be much appreciated

**Comment by rlisowski** [comment]
duplicates #15

**Comment by zeno-mir** [comment]
I wouldn't say it duplicates an issue opened after mine with an almost carbon copy of the description. Anyways, hope the fix for iOS will fix the issue on Android too and that it will be available on homebrew soon.

**Comment by rlisowski** [comment]
@zeno-mir the problem was related to parsing config file, not project type, please try [CLI v2.0.11](https://github.com/phrase/phrase-cli/releases/tag/2.0.11)
