### ISSUE TITLE
format_options invalid key convert_placeholder

### ISSUE THREAD

**Issue by mktomaszewski** [phrase/phrase-cli#15]
Getting ```Targets[0].Params.format_options' has invalid keys: convert_placeholders``` when running phrase pull on an iOS project. The same config works as expected with old phraseapp cli.
Any help will be much appreciated

**Comment by fabioknoedtbcgdv** [comment]
I am having the same problem. It works fine the previous version of `phrase` but not in the latest one

**Comment by rlisowski** [comment]
Thanks for the report, I'm on it.

**Comment by rlisowski** [comment]
Please try [2.0.11](https://github.com/phrase/phrase-cli/releases/tag/2.0.11)

**Comment by mktomaszewski** [comment]
It works! Thank you for a quick response. Would 2.0.11 be available through homebrew too?

**Comment by rlisowski** [comment]
Yes. I will release it today.

**Comment by rlisowski** [comment]
@mktomaszewski done, the release was published and available via Homebrew
