### ISSUE TITLE
Make 'branch' configurable in config-file for pull

### ISSUE THREAD

**Issue by eloo-abi** [phrase/phrase-cli#152]
Hi,

it looks like defining the "branch" in the config file is right now only possible for the push command.

Would be awesome if this could be set also for pull commands in the config-file.

Thanks

**Comment by jablan** [comment]
hi @eloo-abi thanks for the suggestion, definitely makes sense to have it. it's not super trivial as the logic for pull and push is not the same, but I opened an internal ticket, hopefully it will be picked up soon.

**Comment by jablan** [comment]
hi @eloo-abi this feature should now be included in the v2.34 of the cli.
