### ISSUE TITLE
How to use update_description?

### ISSUE THREAD

**Issue by sffc** [phrase/phrase-cli#26]
Thanks for building this nice tool!

On the [Working with continuous integration (CI)](https://help.phrase.com/help/working-with-continuous-integration-ci) page in the Help Center, there is a reference to an update_description option:

> Make sure to set update_translation or update_description if you intend to not only add new values but also update existing values.

However, I can't figure out how or where to use this option in the Phrase CLI.  If I add a new key, then the description associated with that key is uploaded into the Phrase Web UI, but if I add or change the description of an existing key, that change is not reflected when I run `phrase push`.

I tried adding `update_description: true` in multiple places in `.phrase.yml` with no luck, and `phrase push --update_description` does not work either.  Any tips?

I am using the Chrome JSON i18n format.

**Comment by theSoenke** [comment]
Hi @sffc, sorry for the delayed response. Using the `update_description: true` should indeed update existing descriptions. Could you reach out to our support at https://phrase.com/contact/ or via the embedded chat on phrase.com? Then we can take a closer look at your specific configuration. Thanks!

**Comment by sffc** [comment]
Can you tell me where exactly in .phrase.yml to add `update_description: true`?

**Comment by theSoenke** [comment]
Here is an example on how to update descriptions:

```yaml
  push:
    sources:
    - file: ./translations.json
      params:
        file_format: json
        update_descriptions: true
```

The option is called `update_descriptions` instead of `update_description`. I also missed this in my initial reply. Hope this helps. Let me know if you should still run into any issues

**Comment by theSoenke** [comment]
I hope this already resolved your question and I'll go ahead and close this for now.
