### ISSUE TITLE
`phrase init` Loading projects... -panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dauletisataev** [phrase/phrase-cli#27]
I can't initialize phrase by phrase init. Entered the access token, but after waiting about a minute, it throughs error
```Loading projects... -panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x13fd0ca]

goroutine 53 [running]:
github.com/phrase/phrase-go.(*APIResponse).populatePageValues(0xc000295c70)
	/go/pkg/mod/github.com/phrase/phrase-go@v1.0.10/response.go:82 +0x3a
github.com/phrase/phrase-go.NewAPIResponse(0x0, 0xc0002b0100)
```

what could be wrong with what I am doing?

**Comment by rlisowski** [comment]
Hi @dauletisataev,
can you provide more info about which version you use? Please copy&paste `phrase info` output.

**Comment by dauletisataev** [comment]
Hi, @rlisowski, sure, here it is, it has timeout error for some reason -_-

```
ERROR: dial tcp: lookup github.com on 10.1.1.51:53: read udp 192.168.15.239:53185->10.1.1.51:53: i/o timeout
Phrase client version:            2.0.13
Phrase client revision:           72a3b80ea91885b998de44a0199e353b419b9c69
Phrase library revision:          v1.0.10/go.mod
Last change at:                   Mon Aug 3 09:34:49 2020 +0000
Go version:                       go1.14.6
```

**Comment by rlisowski** [comment]
@dauletisataev I notice some clients could get empty 404 last hour due to cluster maintenance, can you retry the init command?

**Comment by dauletisataev** [comment]
@rlisowski  tried again, same behavior, delay after init, one more delay after inserting token, ```Loading projects....``` and again the same error:
```
-panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x13fd0ca]

goroutine 43 [running]:
github.com/phrase/phrase-go.(*APIResponse).populatePageValues(0xc0002cdf40)
```

**Comment by rlisowski** [comment]
That super weird because I just check it manually on a fresh account. Make sure your token has `read` access rights. Also make sure there is no proxy or VPN involved.

**Comment by dauletisataev** [comment]
@rlisowski thanks, I have tried it on another machine with the same token, it works, which is still weird to me. I guess the problem is with my machine, however I don't use any VPN or proxy.
Thank you anyway!

**Comment by rlisowski** [comment]
Ok so if the machine makes the difference then
- which OS is it?
- how you install phrase CLI?
maybe there are others with the same problem.

**Comment by dauletisataev** [comment]
@rlisowski it is 
- **macOs catalina 10.15.5**
- installed CLI using **brew**

**Comment by dauletisataev** [comment]
Ok, I also tried another version of installation, by downloading the client. The same behavior with delay and timeout error. -_-

**Comment by dauletisataev** [comment]
@rlisowski Hi, I figured it out, my DNS configurations were invalid, I only left one ```1.1.1.1```.  Now it works perfectly.

Sorry for bothering)
Thank you for your help!

**Comment by rlisowski** [comment]
All good, I'm glad it's fixed. 


related to #12
