### ISSUE TITLE
iOS - Pulling and pushing plural strings dict creates a duplicate 

### ISSUE THREAD

**Issue by teameh** [phrase/phrase-cli#45]
Pulling and pushing plurals with a strings dict creates a duplicate key with "||localized_key_format" appended. 

I start off the following (plural) copy in Phrase:

<img width="582" alt="image" src="https://user-images.githubusercontent.com/1330668/82313550-cc668080-99c8-11ea-88c1-8a74940d63e3.png">

#### Pull
```
$ phraseapp pull
Downloaded EN to Localizable.stringsdict
```

#### Result: 
```
$ cat Localizable.stringsdict

<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
  <dict>
    <key>my_plural_bicycles_key</key>
    <dict>
      <key>NSStringLocalizedFormatKey</key>
      <string>%#@localized_format_key@</string>
      <key>localized_format_key</key>
      <dict>
        <key>NSStringFormatSpecTypeKey</key>
        <string>NSStringPluralRuleType</string>
        <key>NSStringFormatValueTypeKey</key>
        <string>d</string>
        <key>one</key>
        <string>bicycle</string>
        <key>other</key>
        <string>bicycles</string>
      </dict>
    </dict>
  </dict>
</plist>
```

#### Push: 
```
$ phraseapp push
Uploading Localizable.stringsdict... done!
```

#### Pull again: 
```
$ phraseapp pull
Downloaded EN to Localizable.stringsdict
```

#### Result: 

The key is now duplicated: 

```
$ cat RPX/Base.lproj/Localizable.stringsdict

<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
  <dict>
    <key>my_plural_bicycles_key</key>
    <dict>
      <key>NSStringLocalizedFormatKey</key>
      <string>%#@localized_format_key@</string>
      <key>localized_format_key</key>
      <dict>
        <key>NSStringFormatSpecTypeKey</key>
        <string>NSStringPluralRuleType</string>
        <key>NSStringFormatValueTypeKey</key>
        <string>d</string>
        <key>one</key>
        <string>bicycle</string>
        <key>other</key>
        <string>bicycles</string>
      </dict>
      <key>localized_format_key</key>
      <dict>
        <key>NSStringFormatSpecTypeKey</key>
        <string>NSStringPluralRuleType</string>
        <key>NSStringFormatValueTypeKey</key>
        <string>d</string>
        <key>one</key>
        <string>bicycle</string>
        <key>other</key>
        <string>bicycles</string>
      </dict>
    </dict>
  </dict>
</plist>
```

Also in Phrase:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1330668/82313306-74c81500-99c8-11ea-9a8a-5b4a71701de2.png">

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-cli), and we can take more direct action toward finding a solution.
