### ISSUE TITLE
404 not found - "phrase pull --branch $FROM_BRANCH" for v2.0.24

### ISSUE THREAD

**Issue by pratiksyngenta** [phrase/phrase-cli#59]

**Comment by theSoenke** [comment]
Hi @pratiksyngenta, is it possible that the branch no longer exists on Phrase or that your user does not have permission to access the project? If that's not the case could you contact us at https://phrase.com/contact or via chat or https://phrase.com to figure this out?

**Comment by theSoenke** [comment]
@pratiksyngenta Were you able to solve this issue? I'll close this issue for now but feel free to let me know when you're still running into any problem.
