### ISSUE TITLE
Make updates optional

### ISSUE THREAD

**Issue by ychouinardgc** [phrase/phrase-cli#64]
It's a pain for us to have to update the CLI every time you release an update. Would it be possible to force the update only when you release changes that are not backward compatible?

I'm talking about this error message:
`Please consider updating the Phrase CLI client`

**Comment by theSoenke** [comment]
Hey, thanks for your feedback. We'll have a look at how to make the update info less obtrusive.

**Comment by ychouinardgc** [comment]
I'm pretty sure it's an issue on our side where we incorrectly detect that message as an error output. I don't think you need to change anything
