### ISSUE TITLE
Add instructions on how to run MacOS binaries on m1 Macs 

### ISSUE THREAD

**Issue by LRHJO** [phrase/phrase-cli#65]
Right now there's no clear explanations on how to get the CLI running on m1 Macs. Support said I can run this via rosetta but I'm not sure how exactly. It would be nice to get a workaround while the official m1 binaries are being worked on

**Comment by theSoenke** [comment]
Hey @LRHJO, we're still waiting for the next Golang release before we can publish a native M1 binary. Until then you can run Terminal with Rosetta by going into your applications in Finder, select Terminal and press cmd(⌘)+I, check the “Open using Rosetta” option and then run the CLI from there

**Comment by theSoenke** [comment]
@LRHJO With the golang 1.16 released we now provide native M1 binaries starting with release 2.1.1 https://github.com/phrase/phrase-cli/releases/tag/2.1.1

We'll also add homebrew support as a next step for M1 Macs.
