### ISSUE TITLE
Using different .phrase.yml configuration for pulling/pushing data to Phrase with CLI

### ISSUE THREAD

**Issue by JSEvgeny** [phrase/phrase-cli#68]
Not sure if this is an issue, but I couldn't find any possible solutions to this in documentation.

The idea is to have two Phrase projects for one application and separating push command to upload data only for specific project and not both. For pulling data it's all good since we want to have up-to-date translations from both projects.

I replicated configuration from official documentation [Keeping multiple Phrase projects for one localisation project](https://help.phrase.com/help/keeping-multiple-phrase-projects-for-one-localization-project). It works for pulling/pushing data from/to both projects, but support for pushing only to specific Phrase project would be super nice to have.

EDIT. NVM got different configs working using `--config` flag in CLI v2. Sorry for panic😅

**Comment by theSoenke** [comment]
@JSEvgeny Great that this is also solved for you 😄 I'll try to make sure that this flag will be more prominent in the docs
