### ISSUE TITLE
Uploads Cleanup 400 when upload happened on a branch

### ISSUE THREAD

**Issue by dsimon-onventis** [phrase/phrase-cli#71]
In our project, we are using branching. The `phrase push` happens on a branch.

Now we want to cleanup the deleted keys, like mentioned in #22. But if I run `phrase uploads cleanup`, I'm getting an error:

> Error: 400 Bad Request

Steps to reproduce:

1) run `phrase push --branch tmp` and copy the upload_id
2) run `phrase uploads cleanup --id upload_id`

I suspect it's because there is no option to pass a branch to the uploads cleanup command, and the master branch does not contain the passed upload ID.

P.S. If #22 is fixed and also working on branches, this issue would be obsolete for me.

**Comment by theSoenke** [comment]
Hey @dsimon-onventis, thanks for raising this issue. The cleanup command is right now missing the branch parameter. We will add the branch parameter to the command and I'll keep you updated once it is released.

**Comment by theSoenke** [comment]
This should be resolved with version 2.1.5 https://github.com/phrase/phrase-cli/releases/tag/2.1.5 Now you can just pass in the branch parameter `--branch branch-name` to the cleanup command
