### ISSUE TITLE
Upload and create Job

### ISSUE THREAD

**Issue by GMetaxakis** [phrase/phrase-cli#73]
Hello folks, we've been using your tool and here is a suggestion that would help us with our workflows.

In theory we can use the Phrase API to do those: 
* Upload File
* Get tag for keys
* Create a Job for all those Keys

This as an idea it is very useful but I cannot find a proper way to do this with the phrase-cli to run in a CI, is this something that you believe you can do ? 

Or maybe can we pre-tag the uploaded keys? with `phrase push --tag xx`

**Comment by GMetaxakis** [comment]
for the pre-tag I have created this https://github.com/phrase/phrase-cli/compare/master...GMetaxakis:master

**Comment by GMetaxakis** [comment]
if this gets approved then everyone in their CI can run something like this

```
phrase push --wait true --tag AN_AWESOME_TAG
phrase jobs create --project_id PROJECT_ID --data '{"tags":["AN_AWESOME_TAG"]}'
```

**Comment by theSoenke** [comment]
@GMetaxakis Being able to dynamically tag uploads looks like a quite useful feature. Also thanks for already providing an example implementation. The code in this repository is all generated from https://github.com/phrase/openapi I'll talk with the team about this change and hope that we can add this soon.

**Comment by GMetaxakis** [comment]
@theSoenke I have opened a PR in the `openApi` repo https://github.com/phrase/openapi/pull/143 :)

**Comment by egze** [comment]
Fixed in https://github.com/phrase/openapi/pull/143
