### ISSUE TITLE
There is no "latest" tag in your docker releases

### ISSUE THREAD

**Issue by toinebeg** [phrase/phrase-cli#88]
Hi, 
We use your docker image to integrate phrase in our app. 
I saw that you don't provide a version tagged latest. It's only a minor inconvenience, I used the tag 2.3.0 of your last release but it would be a QOL improvement to have the latest tag. 

Is there a particular reason not to provide it ? 

 You would need to do a second docker push in `build/release.sh` with another image name like `IMAGE_LATEST=${IMAGE_PREFIX}:latest`

**Comment by SergeyMokhov** [comment]
I noticed that too. Latest tag helps automatically stay up to date and I would say is de facto standard for companies  providing docker images.

**Comment by forelabs** [comment]
Thanks for the feedback. We have worked on that part and will make it available in the near future!
