### ISSUE TITLE
Distribute the phrase cli through a package manager on Windows

### ISSUE THREAD

**Issue by skyfrk** [phrase/phrase-cli#89]
Hey there,

life would be easier for us if the phrase cli was available through a package manager on windows. E.g.:

- https://chocolatey.org
- https://docs.microsoft.com/en-us/windows/package-manager/winget/
- https://scoop.sh/

Maybe you can consider supporting any of them in the future?

**Comment by forelabs** [comment]
Hi, first of all I am sorry for the late reply.

Thank you for your request and suggestions.

We have discussed this internally and based on the low number of customers using windows we decided to not work on it for now and will re-evaluate it in the future.
