### ISSUE TITLE
Pluralization with ARB files

### ISSUE THREAD

**Issue by landyrev** [phrase/phrase-cli#90]
Flutter i18n has its own way to encode plurals in ARB files (see [Flutter Internationalization User Guide](https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit)). For example:

```json
{
  "nWombats": "{count,plural, =0{no wombats} other{{count} wombats}}",
  "@nWombats": {
    "description": "A plural message",
    "placeholders": {
      "count": {}
    }
  }
}
```

i18n codegenerator converts this object into handy method `String nWombats(num count)`

But when I use Phrase I'm facing two problems:

1. Plurals are being pulled from Phrase to ARB files as separate i18n keys (like `nWombatsZero`, `nWombatsOne`, `nWombatsOther`), so I have to implement pluralization logic on my own
2. Flutter plurals are not being parsed during the push operation, so I have to work with raw values in the Phrase Editor, which is quite unusable, especially if you work with external translators (see [example screenshot](https://cln.sh/B5Xp1Z))

**Comment by theSoenke** [comment]
Hi @landyrev, I suggest enabling ICU in the settings of your project. You can find this at: Project Settings -> Advanced -> Enable ICU Message format. After that ICU translations will be properly highlighted and should make editing for translators quite a bit easier.

For example, your translation would look like this:

![icu-example](https://user-images.githubusercontent.com/1757301/143260561-00df4fd6-6bb7-4107-84c4-4a86162367c9.png)

In addition, you would have to disable pluralization for all keys that are using ICU. After this you'll also get proper ICU pluralization in your arb file when pulling it.

**Comment by landyrev** [comment]
Thank you, @theSoenke, it helped 🙌

**Comment by landyrev** [comment]
it might be useful to enable this option by default for flutter projects though
