### ISSUE TITLE
When pulling plural strings on iOS, the translation is both in strings and stringsdict files

### ISSUE THREAD

**Issue by zocario** [phrase/phrase-cli#91]
Hello,

On our project we have some plural translations. When we pull the translations using CLI, we do receive the plural translations at the same time:
- in the plural stringsdict file ✅ 
- but also in the strings file (that should only include non-plural strings to me) ❌ 

For example:

In the plural stringsdict:
```
    <key>documents.list.count</key>
    <dict>
      <key>NSStringLocalizedFormatKey</key>
      <string>%#@localized_format_key@</string>
      <key>localized_format_key</key>
      <dict>
        <key>NSStringFormatSpecTypeKey</key>
        <string>NSStringPluralRuleType</string>
        <key>NSStringFormatValueTypeKey</key>
        <string>d</string>
        <key>one</key>
        <string>%d element</string>
        <key>other</key>
        <string>%d elements</string>
        <key>zero</key>
        <string>%d element</string>
      </dict>
    </dict>
```

In the strings file:
```
"documents.list.count.one" = "%d element";

"documents.list.count.other" = "%d elements";

"documents.list.count.zero" = "%d element";
```

**Comment by theSoenke** [comment]
Hey @zocario, to disable pulling the plural forms in the strings file you can disable it with the param `include_pluralized_keys`. In your .phrase.yml you can add it to the params: `include_pluralized_keys: false`

https://help.phrase.com/help/ios-localizable-strings-resources

Let me know if you have any further questions about this

**Comment by theSoenke** [comment]
Closing the ticket for now. Please let me know if this shouldn't work as expected for you
