### ISSUE TITLE
Files and folders created after phrase pull have 0700 permission

### ISSUE THREAD

**Issue by jbranislav** [phrase/phrase-cli#93]
Hello,

After doing `prase pull` all files and folders created in that process have 0700 permission. Please, can this be changed to 0755 for folders and 644 for files or something less restrictive?

This is probably due to https://github.com/phrase/phrase-cli/blob/743050fc33f3679ba8b4a2f1c81f781f2f90598a/cmd/internal/pull.go#L187 and https://github.com/phrase/phrase-cli/blob/743050fc33f3679ba8b4a2f1c81f781f2f90598a/cmd/internal/pull.go#L280

Best regards.

**Comment by theSoenke** [comment]
Hi @jbranislav, that makes total sense to me and I'll look into it to improve the permission for downloaded files

**Comment by sbruhns** [comment]
Hi @jbranislav, we released version https://github.com/phrase/phrase-cli/releases/tag/2.4.6 with less restrict file permissions.
